//// <auto-generated />
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Metadata;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
//using Midterm_ToDoList.Models;

//#nullable disable

//namespace Midterm_ToDoList.Migrations
//{
//    [DbContext(typeof(NAppDbContext))]
//    partial class NAppDbContextModelSnapshot : ModelSnapshot
//    {
//        protected override void BuildModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("ProductVersion", "9.0.0-preview.3.24172.4")
//                .HasAnnotation("Relational:MaxIdentifierLength", 128);

//            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

//            modelBuilder.Entity("Midterm_ToDoList.Models.NToDo", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                    b.Property<string>("Category")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Description")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<bool>("Done")
//                        .HasColumnType("bit");

//                    b.HasKey("Id");

//                    b.ToTable("NToDo");

//                    b.HasData(
//                        new
//                        {
//                            Id = 1,
//                            Category = "Activity",
//                            Description = "Generating Art",
//                            Done = false
//                        });
//                });
//#pragma warning restore 612, 618
//        }
//    }
//}
